apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-app 
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
        - name: my-app-container
          image: nginx:latest # Replace with your container image
          ports:
            - containerPort: 8080 # The port the container listens on
