apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default # Specify your namespace if different
spec:
  type: NodePort
  selector:
    app: backend # This should match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80        # Port that the Service will expose inside the cluster
      targetPort: 8080 # Port on the Pods that the Service should forward traffic to
      nodePort: 30001  # Port on each node that the Service will be accessible externally
