apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-deployment-manager-binding
  namespace: webapp
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: cicd
roleRef:
  kind: Role
  name: db-deployment-manager
  apiGroup: rbac.authorization.k8s.io
