apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv
  namespace: cicd
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:  # Change this based on your environment (e.g., NFS, cloud provider)
    path: /data/jenkins-home  # Adjust the path as needed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
