apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: hostpath-container
    image: busybox
    command: ["sh", "-c", "echo 'Hello from the container' > /mnt/hostpath/message.txt && cat /mnt/hostpath/message.txt && sleep 3600"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/hostpath
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/hostpath
      type: Directory
