apiVersion: v1
kind: Pod
metadata:
  name: shared-data-pod
spec:
  containers:
  - name: container-1
    image: busybox
    command: ["sh", "-c", "echo 'Hello from container-1' > /shared-data/message.txt && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
  - name: container-2
    image: busybox
    command: ["sh", "-c", "cat /shared-data/message.txt && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared-data
  volumes:
  - name: shared-data
    emptyDir: {}
