apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: project_backend:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            value: "db-service"  # Update with the DB service name
          - name: DB_NAME
            value: "example"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: MYSQL_ROOT_PASSWORD
          - name: DB_PORT
            value: "3306"
        ports:
          - containerPort: 8000
