apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: webapp
spec:
  selector:
    app: database
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP  # Use ClusterIP for internal access
