apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: project_proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
