apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: webapp
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  selector:
    app: proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30427  # You can specify a nodePort if desired
